# Generated by Django 4.0.4 on 2022-04-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='limit',
            field=models.FloatField(blank=True, max_length=18, null=True),
        ),
    ]
